apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: ${namespace}
  labels:
    app: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage-${version}
  namespace: ${namespace}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productpage
        version: ${version}
    spec:
      containers:
      - name: productpage
        image: bevyx/demo-bookinfo-productpage:${version}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080